import { fontConfig } from '@/configs/font.config';
import { cn } from '@/lib/utils';
import '@/styles/global.css';
import type { LayoutType } from '@/types/component.types';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const RootLayout: LayoutType = async ({ children, params: { locale } }) => {
	return (
		<html
			lang={locale}
			className={cn(fontConfig.className, 'text-balance antialiased')}
		>
			{children}
		</html>
	);
};

export default RootLayout;
